### PR TITLE
fix: resolves and addition tests for child preStart supervise

### LINKED ISSUE #1384: Bug - Assertion failure caused by exception during pre-start
### Discussed in https://github.com/apache/pekko/discussions/1383

<div type='discussions-op-text'>

<sup>Originally posted by **sadekmunawar** July  2, 2024</sup>
Hi Pekko Team,

Are there any plans to fix this bug in Pekko?
https://discuss.lightbend.com/t/expected-behavior-when-child-actor-throws-an-exception-during-pre-start/10753

Thank you</div>

### PR DESCRIPTION
**Pull request by Roiocam**
Related with #1384 and resolves #1384, some of code contributed by @sadekmunawar 

if PR can reproducer this issue, the ci checks will be unable to successd: https://github.com/apache/pekko/actions/runs/9770536752/job/26971887726?pr=1385

### CODE REVIEW

**Comment by Roiocam** [comment]
From the perspective of stack frame, the problem lies in the handling:

https://github.com/apache/pekko/blob/46c557424d19bb2d07adf2fbd55351a8187ff359/actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala#L160

```

[ERROR] [07/03/2024 09:46:12.113] [SupervisorSpec-pekko.actor.default-dispatcher-5] [pekko://SupervisorSpec/user/$a/$a] changing Recreate into Create after org.apache.pekko.actor.ActorInitializationException: pekko://SupervisorSpec/user/$a/$a: exception during creation, root cause message: [deliberate test failure]
[ERROR] [07/03/2024 09:46:12.114] [SupervisorSpec-pekko.actor.default-dispatcher-6] [pekko://SupervisorSpec/user/$a/$a] assertion failed
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:264)
	at org.apache.pekko.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:160)
	at org.apache.pekko.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:158)
	at org.apache.pekko.actor.ActorCell.faultCreate(ActorCell.scala:420)
	at org.apache.pekko.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:96)
	at org.apache.pekko.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:92)
	at org.apache.pekko.actor.ActorCell.faultRecreate(ActorCell.scala:420)
	at org.apache.pekko.actor.ActorCell.invokeAll$1(ActorCell.scala:526)
	at org.apache.pekko.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at org.apache.pekko.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:297)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:232)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:245)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

File: actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala [hunk 1]
```diff
@@ -643,7 +643,7 @@ private[pekko] class ActorCell(
     def failActor(): Unit =
       if (_actor != null) {
         clearActorFields(actor, recreate = false)
-        setFailedFatally()
+        setFailed(actor.self)
```
Comment (Roiocam) [inline actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala:646]: I am not sure if this change will break other cases or not, I will investigate later.

relate PR:

- https://github.com/akka/akka/pull/29098/files
- https://github.com/akka/akka/pull/27614/files

**Comment by He-Pin** [comment]
I think we can attach a test case for this, will look into this over the weekend.

File: actor-tests/src/test/scala/org/apache/pekko/actor/SupervisorSpec.scala [hunk 2]
```diff
@@ -95,6 +95,14 @@ object SupervisorSpec {
     }
   }
 
+  class Child(cnt: Int) extends Actor {
```
Comment (He-Pin) [inline actor-tests/src/test/scala/org/apache/pekko/actor/SupervisorSpec.scala:98]: seems like we need closing over the origin AtomicInteger because the restart will keep the actor state instead of recreate.

File: actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala (hunk 1 above)
Comment (Roiocam) [reply actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala]: After investigation, we can not set the fault state here... otherwise, we can distinguish between fatal and normal fault

Comment (raboof) [reply actor/src/main/scala/org/apache/pekko/actor/ActorCell.scala]: (these links to Akka PRs are OK because they're old, pre-BSL PRs :) )

File: actor-tests/src/test/scala/org/apache/pekko/actor/SupervisorSpec.scala (hunk 2 above)
Comment (Roiocam) [reply actor-tests/src/test/scala/org/apache/pekko/actor/SupervisorSpec.scala:98]: I think this is ok... Because we were using creator.

https://github.com/apache/pekko/blob/46c557424d19bb2d07adf2fbd55351a8187ff359/actor/src/main/scala/org/apache/pekko/actor/Props.scala#L87-L88

**Comment by Roiocam** [comment]
@sadekmunawar Hi, my unit test partly refers to your code in #1383 links.

Would you like to contribute this to the Pekko community?

**Comment by Roiocam** [comment]
> Would you like to contribute this to the Pekko community?

@pjfanning Am I doing this correctly, may I ask?

**Comment by pjfanning** [comment]
> > Would you like to contribute this to the Pekko community?
> 
> @pjfanning Am I doing this correctly, may I ask?

The test code was written by https://discuss.lightbend.com/u/nodeninja/summary

@sadekmunawar can you confirm if that is you? We received your iCLA.

**Comment by sadekmunawar** [comment]
> The test code was written by https://discuss.lightbend.com/u/nodeninja/summary
> 
> @sadekmunawar can you confirm if that is you? We received your iCLA.
> 

@pjfanning yes, that's me. After finding the bug, I wrote that test for a solution I implemented. My solution converts the `FatallyFailed` into a case class and attaches an Optional ActorRef to it.

I also wrote a scala version of this test in `ActorLifCyleSpec`. Feel free to use either version of the test
`"must not break supervisor strategy due to unhandled exception in preStart" in {
  val id = newUuid.toString
  val gen = new AtomicInteger(0)
  val maxRetryNum = 3

  val childProps = Props(new LifeCycleTestActor(testActor, id, gen) {
    override def preStart(): Unit = {
      report("preStart")
      throw new Exception("test exception")
    }
  }).withDeploy(Deploy.local)

  val supervisorStrategy: SupervisorStrategy =
    OneForOneStrategy(maxNrOfRetries = maxRetryNum, timeout.duration) {
      case _: ActorInitializationException => SupervisorStrategy.Restart
      case _                               => SupervisorStrategy.Escalate
    }
  val supervisor =  system.actorOf(Props(classOf[Supervisor], supervisorStrategy))
  Await.result((supervisor ? childProps).mapTo[ActorRef], timeout.duration)

  (0 to maxRetryNum).foreach(i => {
    expectMsg(("preStart", id, i))
  })
  expectNoMessage()
  system.stop(supervisor)
}`

File: actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala [hunk 3]
```diff
@@ -214,34 +214,34 @@ private[pekko] trait FaultHandling { this: ActorCell =>
   @InternalStableApi
   final def handleInvokeFailure(childrenNotToSuspend: immutable.Iterable[ActorRef], t: Throwable): Unit = {
     // prevent any further messages to be processed until the actor has been restarted
-    if (!isFailed)
```
Comment (pjfanning) [inline actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala:217]: why is this check not needed?

Comment (laglangyue) [reply actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala:217]: > why is this check not needed?

he move the check to match case

**Review by pjfanning — APPROVED** [review]
lgtm

**Comment by laglangyue** [comment]
lgtm.
Although I have read the relevant code, I did not delve into testing and debugging

File: actor-tests/src/test/scala/org/apache/pekko/actor/ActorLifeCycleSpec.scala [hunk 4]
```diff
@@ -160,6 +160,33 @@ class ActorLifeCycleSpec extends PekkoSpec with BeforeAndAfterEach with Implicit
       a ! "hello"
       expectMsg(42)
     }
+
+    "not break supervisor strategy due to unhandled exception in preStart" in {
```
Comment (Roiocam) [inline actor-tests/src/test/scala/org/apache/pekko/actor/ActorLifeCycleSpec.scala:164]: Contributed by @sadekmunawar

**Comment by Roiocam** [comment]
> I also wrote a scala version of this test in `ActorLifCyleSpec`. Feel free to use either version of the test

Thanks, I have updated this PR and verified it works in locally

File: actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala (hunk 3 above)
Comment (Roiocam) [reply actor/src/main/scala/org/apache/pekko/actor/dungeon/FaultHandling.scala:217]: the original code didn't use `setFailed()`, so we have no chance to update `actorRef`, and then we will get an assertion failed(the original issue)

This PR used `setFailed()` in exception handling, but we still need send a system message to ourself(to continue handling faults).

I think this check is the real problem that led to the original issue, and my PR removal check is to fix this problem.

**Comment by pjfanning** [comment]
@Roiocam should we backport this to this 1.0.x branch?

**Comment by Roiocam** [comment]
> @Roiocam should we backport this to this 1.0.x branch?

Of course, this is a bug. backport on #1396

**Comment by sadekmunawar** [comment]
It looks like [the checks](https://github.com/apache/pekko/actions/runs/9835390068/job/27148930769) did not run the tests in `SupervisorHierarchySpec`.

When I ran the tests locally, two tests in `SupervisorHierarchySpec` failed.

-  `handle failure in creation when supervision strategy returns Resume and Restart`
- `survive being stressed`


Can someone check if these two unit tests pass?

**Comment by pjfanning** [comment]
> It looks like [the checks](https://github.com/apache/pekko/actions/runs/9835390068/job/27148930769) did not run the tests in `SupervisorHierarchySpec`.
> 
> When I ran the tests locally, two tests in `SupervisorHierarchySpec` failed.
> 
> * `handle failure in creation when supervision strategy returns Resume and Restart`
> * `survive being stressed`
> 
> Can someone check if these two unit tests pass?

Those tests are tagged as long-running tests. Maybe such tests are not run by default.

Did those tests fail before this PR was added?

**Comment by sadekmunawar** [comment]
> Did those tests fail before this PR was added?

No, they passed in my local workspace before this PR was added. Unless there's something wrong with my local setup, this PR is the likely cause of the failures. I ran into issues with these two unit tests when experimenting with my own fix.

**Comment by Roiocam** [comment]
I will investigate it. :)

**Comment by Roiocam** [comment]
both `survive being stressed` and `handle failure in creation when supervision strategy returns Resume and Restart
` has passes in my local by using #1399
